apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: paas-admin
  namespace: openshift-gitops
spec:
  destinations:
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc 
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc  
  - name: sno2-stolarware
    namespace: openshift-gitops
    server: https://api.sno2.stolarek.org.pl:6443
  sourceRepos:
  - https://github.com/stolarware/paas-acm.git