apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sno2-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - stolarware
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - c02t-bec-dk
