apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-paas-projects-init-app
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: appset-chart
    repoURL: https://github.com/stolarware/newnamespace-chart.git
    targetRevision: main
    helm:
      valueFiles:
        - ../values/clusters/sno/projects.yaml
  project: paas-admin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
