apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-remote-resources-init-app
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: sno1/applications/sno/remote-resources
    repoURL: https://github.com/stolarware/paas-acm.git
    targetRevision: master
  project: openshift-admin
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - FailOnSharedResource=true
